version: '3'

services:
  client:
    build: ./client
    depends_on:
      - api
    environment:
      - HOST=0.0.0.0
      - PORT=3000
    volumes:
      - ./client:/app
    ports:
      - 4000:3000
    command: yarn nuxt

  api:
    build: ./api
    volumes:
      - ./api:/app
    ports:
      - 4001:3000
    command: yarn json-server --watch db.json --host 0.0.0.0
