services:
  client:
    command: npm run dev
    environment:
      NUXT_HOST: 0.0.0.0
      NUXT_PORT: 8080
    image: node:20-alpine
    ports:
      - 8080:8080
    volumes:
      - ./client:/app
    working_dir: /app
